# permissions for end users to view students.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: student-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
  name: student-viewer-role
rules:
- apiGroups:
  - k8s.unito.it
  resources:
  - students
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k8s.unito.it
  resources:
  - students/status
  verbs:
  - get
